#!/usr/bin/env python3
from test import try_and_exception
from test import sys_function
import sys

def main():
	try_and_exception()
	sys_function()

if __name__ == '__main__':
	main()
	sys.exit(0)